"""Initial migration

Revision ID: 11681ed371e8
Revises: 
Create Date: 2023-03-18 16:57:59.000425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11681ed371e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class",
        sa.Column("class_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("links", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("class_id"),
    )
    op.create_table(
        "user",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("salt", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("email", "user_id"),
    )
    op.create_table(
        "message",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("class_id", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.class_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "note",
        sa.Column("note_id", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("class_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.class_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("note_id"),
    )
    op.create_table(
        "tag",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("class_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.class_id"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "user_class",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("class_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.class_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "class_id"),
    )
    op.create_table(
        "note_tag",
        sa.Column("note_id", sa.String(), nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.note_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_name"],
            ["tag.name"],
        ),
        sa.PrimaryKeyConstraint("note_id", "tag_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("note_tag")
    op.drop_table("user_class")
    op.drop_table("tag")
    op.drop_table("note")
    op.drop_table("message")
    op.drop_table("user")
    op.drop_table("class")
    # ### end Alembic commands ###
