"""remove salt

Revision ID: 34a01b321880
Revises: 11681ed371e8
Create Date: 2023-03-18 22:58:27.615962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a01b321880'
down_revision = '11681ed371e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
