"""Make class link its own model

Revision ID: 75a27385585d
Revises: 4b03fa623fe8
Create Date: 2023-04-21 16:58:09.290961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a27385585d'
down_revision = '4b03fa623fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('link_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('links')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('links', sa.VARCHAR(), nullable=True))

    op.drop_table('link')
    # ### end Alembic commands ###
