"""delete tags

Revision ID: a5af8e414344
Revises: 75a27385585d
Create Date: 2023-05-21 13:20:17.607514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5af8e414344'
down_revision = '75a27385585d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('class_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('note_tag',
    sa.Column('note_id', sa.VARCHAR(), nullable=False),
    sa.Column('tag_name', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.note_id'], ),
    sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], ),
    sa.PrimaryKeyConstraint('note_id', 'tag_name')
    )
    # ### end Alembic commands ###
