"""empty message

Revision ID: cb16188a22d0
Revises: a5af8e414344
Create Date: 2023-05-21 16:04:41.959898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb16188a22d0'
down_revision = 'a5af8e414344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bot', sa.Boolean(), nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('is_bot')

    # ### end Alembic commands ###
